### ISSUE TITLE
Error when build the project 

### ISSUE THREAD

**Issue by hamza94max** [hamza94max/Wazaker#25]
@MahmoudMabrok 

When building the project this error displayed I tried many solutions but not working.

_Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'maven2(http://api.tplmaps.com:8081/artifactory/example-repo-local/)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.0.2/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details._ 

**Look at gradle or something**  [gradle](https://github.com/hamza94max/Wazaker/blob/master/build.gradle)

**Comment by hamza94max** [comment]
Fixed ^_^ 
thanks

**Comment by MahmoudMabrok** [comment]
Could you share the solution and why issue was occurred?

**Comment by hamza94max** [comment]
change
 distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-**all**.zip to distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-**bin**.zip

in **gradle-wrapper.properties** file 

and delete unused dependency in gradle file
